/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCaixaRouteImport } from './routes/_app/caixa'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppOrdensRouteImport } from './routes/_app/ordens'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppServicosRouteImport } from './routes/_app/servicos'
import { Route as AppWhatsappRouteImport } from './routes/_app/whatsapp'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrdensIdImprimirRouteImport } from './routes/_app/ordens.$id.imprimir'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensRoute = AppOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrdensIdImprimirRoute = AppOrdensIdImprimirRouteImport.update({
  id: '/$id/imprimir',
  path: '/$id/imprimir',
  getParentRoute: () => AppOrdensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/caixa': typeof AppCaixaRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/ordens': typeof AppOrdensRouteWithChildren
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/servicos': typeof AppServicosRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/caixa': typeof AppCaixaRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/ordens': typeof AppOrdensRouteWithChildren
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/servicos': typeof AppServicosRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/caixa': typeof AppCaixaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/ordens': typeof AppOrdensRouteWithChildren
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/servicos': typeof AppServicosRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/ordens'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/whatsapp'
    | '/api/auth/$'
    | '/ordens/$id/imprimir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/ordens'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/whatsapp'
    | '/'
    | '/api/auth/$'
    | '/ordens/$id/imprimir'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/caixa'
    | '/_app/categorias'
    | '/_app/clientes'
    | '/_app/ordens'
    | '/_app/produtos'
    | '/_app/relatorios'
    | '/_app/servicos'
    | '/_app/whatsapp'
    | '/_app/'
    | '/api/auth/$'
    | '/_app/ordens/$id/imprimir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caixa': {
      id: '/_app/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens': {
      id: '/_app/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AppOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ordens/$id/imprimir': {
      id: '/_app/ordens/$id/imprimir'
      path: '/$id/imprimir'
      fullPath: '/ordens/$id/imprimir'
      preLoaderRoute: typeof AppOrdensIdImprimirRouteImport
      parentRoute: typeof AppOrdensRoute
    }
  }
}

interface AppOrdensRouteChildren {
  AppOrdensIdImprimirRoute: typeof AppOrdensIdImprimirRoute
}

const AppOrdensRouteChildren: AppOrdensRouteChildren = {
  AppOrdensIdImprimirRoute: AppOrdensIdImprimirRoute,
}

const AppOrdensRouteWithChildren = AppOrdensRoute._addFileChildren(
  AppOrdensRouteChildren,
)

interface AppRouteChildren {
  AppCaixaRoute: typeof AppCaixaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppOrdensRoute: typeof AppOrdensRouteWithChildren
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppServicosRoute: typeof AppServicosRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaixaRoute: AppCaixaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppClientesRoute: AppClientesRoute,
  AppOrdensRoute: AppOrdensRouteWithChildren,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppServicosRoute: AppServicosRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
